# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.ID, "username").send_keys("Ram")
    self.driver.find_element(By.ID, "password").send_keys("Ram@1234")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "LogOut").click()

driver = webdriver.Chrome()
driver.implicitly_wait(30)
driver.maximize_window()
driver.get("http://127.0.0.1:8000/")
driver.set_window_size(1552, 880)
driver.find_element(By.LINK_TEXT, "Sign In").click()
driver.implicitly_wait(300000)
driver.find_element(By.ID, "username").send_keys("Ram")
driver.find_element(By.ID, "password").send_keys("Ram@1234")
driver.find_element(By.ID, "password").click()
driver.implicitly_wait(300000)
driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(4)").click()
driver.implicitly_wait(300000)
driver.find_element(By.LINK_TEXT, "LogOut").click()
