# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditMessages():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editMessages(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.ID, "username").send_keys("Sai")
    self.driver.find_element(By.ID, "password").send_keys("Sai@12345")
    self.driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.NAME, "message").click()
    self.driver.find_element(By.NAME, "message").send_keys("Predators")
    self.driver.find_element(By.NAME, "message").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".sender:nth-child(4) a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "LogOut").click()
    self.driver.close()


driver = webdriver.Chrome()
driver.implicitly_wait(30)
driver.maximize_window()
driver.get("http://127.0.0.1:8000/")
driver.set_window_size(1552, 880)
driver.find_element(By.LINK_TEXT, "Sign In").click()
driver.implicitly_wait(300000)
driver.find_element(By.ID, "username").send_keys("Sai")
driver.find_element(By.ID, "password").send_keys("Sai@12345")
driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(4)").click()
driver.implicitly_wait(300000)
driver.find_element(By.LINK_TEXT, "Movies").click()
driver.implicitly_wait(300000)
driver.find_element(By.NAME, "message").click()
driver.implicitly_wait(300000)
driver.find_element(By.NAME, "message").send_keys("Predators")
driver.implicitly_wait(300000)
driver.find_element(By.NAME, "message").send_keys(Keys.ENTER)
driver.find_element(By.CSS_SELECTOR, ".sender:nth-child(4) a").click()
driver.implicitly_wait(300000)
driver.find_element(By.CSS_SELECTOR, ".w-full").click()
driver.implicitly_wait(300000)
driver.find_element(By.LINK_TEXT, "Home").click()
driver.implicitly_wait(300000)
driver.find_element(By.LINK_TEXT, "LogOut").click()
driver.implicitly_wait(300000)
driver.close()