# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBanUser():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_banUser(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Sign-in As Moderator").click()
    self.driver.find_element(By.ID, "modarator_name").click()
    self.driver.find_element(By.ID, "modarator_name").send_keys("Yash")
    self.driver.find_element(By.ID, "modarator_id").click()
    self.driver.find_element(By.ID, "modarator_id").send_keys("123")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Yash@123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500:nth-child(5)").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".w-full").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "LogOut").click()
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Sam")
    self.driver.find_element(By.ID, "password").send_keys("Sam@1234")
    self.driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.NAME, "join").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "LogOut").click()
    self.driver.close()

driver = webdriver.Chrome()
driver.implicitly_wait(30)
driver.maximize_window()
driver.get("http://127.0.0.1:8000/")
driver.set_window_size(1552, 832)
driver.find_element(By.LINK_TEXT, "Sign-in As Moderator").click()
driver.find_element(By.ID, "modarator_name").click()
driver.find_element(By.ID, "modarator_name").send_keys("Yash")
driver.find_element(By.ID, "modarator_id").click()
driver.find_element(By.ID, "modarator_id").send_keys("123")
driver.find_element(By.ID, "password").click()
driver.find_element(By.ID, "password").send_keys("Yash@123")
driver.find_element(By.CSS_SELECTOR, ".bg-blue-500:nth-child(5)").click()
driver.find_element(By.LINK_TEXT, "Movies").click()
driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(5) a").click()
driver.find_element(By.CSS_SELECTOR, ".w-full").click()
driver.find_element(By.LINK_TEXT, "Home").click()
driver.find_element(By.LINK_TEXT, "LogOut").click()
driver.find_element(By.LINK_TEXT, "Sign In").click()
driver.find_element(By.ID, "username").click()
driver.find_element(By.ID, "username").send_keys("Sam")
driver.find_element(By.ID, "password").send_keys("Sam@1234")
driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(4)").click()
driver.find_element(By.LINK_TEXT, "Movies").click()
driver.find_element(By.NAME, "join").click()
driver.find_element(By.LINK_TEXT, "Home").click()
driver.find_element(By.LINK_TEXT, "LogOut").click()
driver.close()